apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha
  labels:
    dagon.io/managed: "true"
    dagon.io/tenant-id: "11111111-1111-1111-1111-111111111111"
    dagon.io/compliance-tier: "soc2"
    dagon.io/environment: "dev"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-writable-rootfs
  namespace: team-alpha
spec:
  containers:
    - name: app
      image: nginx:1.25.3
      securityContext:
        readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-missing-rootfs-setting
  namespace: team-alpha
spec:
  containers:
    - name: app
      image: nginx:1.25.3
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-readonly-rootfs
  namespace: team-alpha
spec:
  containers:
    - name: app
      image: nginx:1.25.3
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: tmp
      emptyDir: {}
