apiVersion: v1
kind: Namespace
metadata:
  name: hipaa-namespace-no-encryption
  labels:
    dagon.io/managed: "true"
    dagon.io/compliance-tier: "hipaa"
    dagon.io/tenant-id: "22222222-2222-2222-2222-222222222222"
    dagon.io/environment: "prod"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gdpr-namespace-no-encryption
  labels:
    dagon.io/managed: "true"
    dagon.io/compliance-tier: "gdpr"
    dagon.io/tenant-id: "22222222-2222-2222-2222-222222222222"
    dagon.io/environment: "prod"
---
apiVersion: v1
kind: Namespace
metadata:
  name: soc2-namespace-no-encryption
  labels:
    dagon.io/managed: "true"
    dagon.io/compliance-tier: "soc2"
    dagon.io/tenant-id: "22222222-2222-2222-2222-222222222222"
    dagon.io/environment: "dev"
---
apiVersion: v1
kind: Namespace
metadata:
  name: hipaa-namespace-with-encryption
  labels:
    dagon.io/managed: "true"
    dagon.io/compliance-tier: "hipaa"
    dagon.io/tenant-id: "22222222-2222-2222-2222-222222222222"
    dagon.io/environment: "prod"
  annotations:
    dagon.io/encryption: "at-rest"
